name: mawaqit_tv_l10n
description: Localization package for Mawaqit TV Android application containing translations in 40+ languages
version: 1.0.0
homepage: https://mawaqit.net

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  generate: true
  assets:
    - l10n/ 